config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shortener.urls', namespace='shortener')),
]

shortener/urls.py
from django.urls import path

from . import views

app_name = 'shortener'

urlpatterns = [
    path('', views.MainPageView.as_view(), name='main_page'),
    path('create_url/', views.CreateShortenedUrlView.as_view(), name='create_url'),
    path('shorted_urls/', views.UrlListView.as_view(), name='url_list'),
    path('shorted_url/<pk>', views.UrlDetailView.as_view(), name='url_detail'),
    path('<str:url_part>/', views.UrlRedirectView.as_view(), name='redirect'),
]

shortener/models.py
from django.db import models


class ShortenedUrl(models.Model):
    original_url = models.URLField(max_length=1000)
    shortened_url = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.shortened_url

shortener/forms.py
from django import forms

from .models import ShortenedUrl


class CreateShortenedUrlForm(forms.ModelForm):
    class Meta:
        model = ShortenedUrl
        fields = ('original_url',)

shortener/views.py
import random
import string

from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView, DetailView

from .forms import CreateShortenedUrlForm
from .models import ShortenedUrl
from config.settings import DOMAIN


class MainPageView(View):

    def get(self, request):
        return render(request, 'shortener/main.html')


def generate_shortened_url():
    return DOMAIN + '/' + ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(6))


class CreateShortenedUrlView(View):

    def get(self, request):
        form = CreateShortenedUrlForm()
        return render(request, 'shortener/create_url.html', {'form': form})

    def post(self, request):
        form = CreateShortenedUrlForm(request.POST)
        shortened_url = None
        new_url_id = None
        if form.is_valid():
            existed_urls = [url.shortened_url for url in ShortenedUrl.objects.all()]
            while True:
                shortened_url = generate_shortened_url()
                if shortened_url not in existed_urls:
                    break
            new_url = form.save(commit=False)
            new_url.shortened_url = shortened_url
            new_url.original_url = form.cleaned_data['original_url']
            new_url.save()
            new_url_id = new_url.pk

        return render(request, 'shortener/create_url.html', {'form': form,
                                                             'shortened_url': shortened_url,
                                                             'new_url_id': new_url_id})


class UrlListView(ListView):
    model = ShortenedUrl
    context_object_name = 'url_list'


class UrlDetailView(DetailView):
    model = ShortenedUrl
    context_object_name = 'url'


class UrlRedirectView(View):
    def get(self, request, url_part):
        url = ShortenedUrl.objects.get(shortened_url=f'{DOMAIN}/{url_part}')
        return redirect(url.original_url)

shortener/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <a href="{% url 'shortener:main_page' %}" type="button" class="btn btn-outline-dark">Home</a>
    <div class="container">
        <div class="row justify-content-md-center">
            {% block content %}
            {% endblock content %}
        </div>
    </div>

</body>
</html>

shortener/templates/shortener/create_url.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
	Create URL
{% endblock title %}


{% block content %}
	<div class="col-6">
		<h1>Creating a new shortened url</h1>

		<form method="post">
			{% csrf_token %}
			{{ form|crispy }}
			<button type="submit" class="btn btn-outline-dark">Create</button>
		</form>

		{% if shortened_url %}
			<div class="alert alert-success" role="alert"> 
					URL successfully created: <a href="{% url 'shortener:url_detail' new_url_id %}">{{ shortened_url }}</a>
			</div>
		{% endif %}

	</div>
{% endblock content %}

shortener/templates/shortener/main.html
{% extends "base.html" %}

{% block title %}
	Url Shortener
{% endblock title %}


{% block content %}
	<div class="col-6">
		<h1>Url Shortener</h1>

		<p>Here you can create a new shortened url</p>
		<a href="{% url 'shortener:create_url' %}" type="button" class="btn btn-outline-dark">Create</a>
		<p>Here you can see the list of shortened urls</p>
		<a href="{% url 'shortener:url_list' %}" type="button" class="btn btn-outline-dark">View the list</a>
	</div>
{% endblock content %}

shortener/templates/shortener/shortenedurl_detail.html
{% extends "base.html" %}

{% block title %}
    URL
{% endblock title %}

{% block content %}
    
    <div class="col-6">

        <h5>Original URL: </h5> <p>{{ url.original_url }}</p>
        <a href="{{ url.original_url }}" type="button" class="btn btn-outline-dark">Go to the web site</a>
    </div>
    
{% endblock %}

shortener/templates/shortener/shortenedurl_list.html
{% extends "base.html" %}

{% block title %}
    URLs
{% endblock title %}

{% block content %}
    
    <div class="col-6">
        <h2>URLs:</h2>

        <ul class="list-group">
            {% for url in url_list %}
                <li class="list-group-item">
                    <a href="{% url 'shortener:url_detail' url.pk %}">{{ url.shortened_url }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}